# Generated by Django 5.1.4 on 2025-01-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('centre_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
