# Generated by Django 5.1.4 on 2025-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_centre_no_certificate_centre_no1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.IntegerField(),
        ),
    ]
